
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import '../globals.css'
import Navbar from "../components/navbar/Navbar";
import ClientsOnly from "../components/ClientsOnly";

import ToasterProvider from "../providers/ToasterProvider";
import ConditionalBottomNav from "../components/navbar/ConditionalBottomNav";

const font  = Raleway({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientsOnly>
          <ToasterProvider />
          <Navbar />
        </ClientsOnly>

        {children}
      <ConditionalBottomNav />
      </body>
    </html>
  );
}
