import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "../globals.css";

import Navbar from "../components/navbar/Navbar";
import ClientsOnly from "../components/ClientsOnly";
import ToasterProvider from "../providers/ToasterProvider";
import ConditionalBottomNav from "../components/navbar/ConditionalBottomNav";

import { auth } from "@/lib/auth";
import { headers } from "next/headers";

const font = Raleway({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ClientLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // ✅ headers() is sync
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  return (
    <html lang="en">
      <body className={font.className}>
        <ClientsOnly>
          <ToasterProvider />
          <Navbar session={session}/>
        </ClientsOnly>

        {children}

        <ConditionalBottomNav />
      </body>
    </html>
  );
}
